services:
  backend:
    image: python-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - hma-python-network
    
  
networks:
  hma-python-network:
    driver: bridge